name: flutter_viz
description: "A new Flutter application."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.9.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  nb_utils: ^7.1.4
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  intl: ^0.20.2
  #flutter_treeview: ^1.0.7+1
  flutter_treeview:
    git:
      url: https://github.com/kee-org/flutter_treeview.git
      ref: master # branch name
  animated_tree_view: ^2.3.0
  flutter_speed_dial: ^7.0.0
  reorderables: ^0.6.0
  syncfusion_flutter_sliders: ^30.1.39
  direct_select_flutter: ^1.1.1
  url_launcher: ^6.3.1
  animated_icon_button: ^1.0.2
  image_picker: ^1.1.2
  hovering: ^1.0.4
  provider: ^6.1.5
  google_sign_in: ^7.1.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_analytics: ^11.5.0
  lottie: ^3.3.1
  get_it: ^8.0.3
  fl_chart: ^1.0.0
  flutter_dotenv: ^5.2.1
  web: ^1.1.1

  # Google maps web
  google_maps: ^8.1.1
  # Youtube player
  youtube_player_iframe: ^5.2.1
  #  youtube_plyr_iframe: ^2.0.7
  # Audio Player Lib
  just_audio: ^0.10.4
  rxdart: ^0.28.0
  # Video Player
  video_player: ^2.10.0
  # Chart
  #  charts_flutter: ^0.12.0
  readmore: ^3.0.0
  # Smooth page indicator
  smooth_page_indicator: ^1.2.1
  # SVG Icons
  flutter_svg: ^2.2.0
  # Zoom View
  zoom_widget: ^2.0.1
  # code format
  dart_style: ^3.1.0
  # rating bar
  flutter_rating_bar: ^4.0.1
  # Vector Icons
  flutter_vector_icons: ^2.0.0
  # Flutter toast
  fluttertoast: ^8.2.12
  # OTP TextField
  flutter_otp_text_field: ^1.5.1+1
  # Package Information
  package_info_plus: ^8.3.0
  # Switch
  flutter_switch: ^0.3.2
  screenshot: ^3.0.0

  cached_network_image: ^3.4.1

  #File Picker
  file_picker: ^10.2.0
  image_picker_web: ^4.0.0

  #Recaptcha
  g_recaptcha_v3: ^1.0.0

  #Connectivity
  http: ^1.4.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.7.1
  build_runner: ^2.5.0

  #flutter packages pub run build_runner build --delete-conflicting-outputs
  #flutter run -d chrome --web-port 5000

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/devices/
    - images/files/
    - images/svgicons/
    - images/widgetsInformation/
    - images/flag/
    #- assets/dotenv

  fonts:
    - family: Inter
      fonts:
        - asset: font/Inter-Regular.ttf
        - asset: font/Inter-Bold.ttf
        - asset: font/Inter-Medium.ttf
        - asset: font/Inter-SemiBold.ttf
